name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  build-and-push:
    permissions:
      packages: write
      contents: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build and push containers
      run: |
        set -axe

        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        TAG=${GITHUB_REF##*/} make docker-build docker-push
